[colors.primary]
background = '#00141a' #color.base04
foreground = '#839495' #color.fg

[colors.normal]
black   = '#00141a' #color.base04
red     = '#dc312e' #color.red
green   = '#859900' #color.green
yellow  = '#b38600' #color.yellow
blue    = '#278bd3' #color.blue
magenta = '#d33682' #color.magenta
cyan    = '#2aa298' #color.cyan
white   = '#ede7d4' #color.base2

[colors.bright]
black   = '#002d38' #color.base03
red     = '#f65351' #color.red300
green   = '#b7fa00' #color.green300
yellow  = '#ffbf00' #color.yellow300
blue    = '#47adf5' #color.blue300
magenta = '#f254a1' #color.magenta300
cyan    = '#2beede' #color.cyan300

[font.normal]
family = "FiraCode Nerd Font"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[mouse.bindings]]
action = "None"
mouse = "Middle"
